POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVua2VsaSIsImlkIjoiNjg3NGYxYmJiMWUxNThhMzY0ZmE0ZDY5IiwiaWF0IjoxNzUyNjUyNjczLCJleHAiOjE3NTI2NTYyNzN9.x4FUbjBRuwflUuZ_TBO1UhtrD7WjinZTfDHQh-gfoeI

{
  "title": "Tää vois olla yksi blogi",
  "author": "Mielipiteinen Sirpanen",
  "url": "kommentti.fi",
  "likes": 2,
  "userId": "685e99688937ae64ad307470"
}