POST http://localhost:3003/api/blogs
Content-Type: application/json


{
  "title": "Kukat kastuu",
  "author": "Kastelija Keinonen",
  "url": "kukka.fi",
  "likes": 999,
  "userId": "685e99688937ae64ad307470"
}